import PyInstaller.__main__

PyInstaller.__main__.run([
    'main.py',
    '--onefile',
    '--windowed',
    '--name=LANMonitor',
    '--hidden-import=pywt._extensions._cwt',
    '--hidden-import=scapy.layers.l2',
    '--hidden-import=scapy.layers.inet',
    '--hidden-import=scapy.layers.dhcp',
    '--hidden-import=scapy.layers.dns',
    '--hidden-import=scapy.layers.dot11',
    '--hidden-import=scapy.layers.gprs',
    '--hidden-import=scapy.layers.hsrp',
    '--hidden-import=scapy.layers.isakmp',
    '--hidden-import=scapy.layers.l2tp',
    '--hidden-import=scapy.layers.mgcp',
    '--hidden-import=scapy.layers.mobileip',
    '--hidden-import=scapy.layers.rip',
    '--hidden-import=scapy.layers.rtp',
    '--hidden-import=scapy.layers.sctp',
    '--hidden-import=scapy.layers.skinny',
    '--hidden-import=scapy.layers.smb',
    '--hidden-import=scapy.layers.snmp',
    '--hidden-import=scapy.layers.tftp',
    '--hidden-import=scapy.layers.x509',
    '--hidden-import=nmap'
])
